apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcx-public-ui-web
  namespace: arc-x-public-ui-236-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcx-public-ui-web

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: arcx-public-ui-web
    spec:
      containers:
      - name: web
        image: $CI_REGISTRY_IMAGE/public-ui-web:$CI_COMMIT_SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: arcx-public-ui-configmap
        env:
        - name: REDEPLOY_META
          value: $CI_JOB_ID-$CI_COMMIT_SHA
        - name: WEB_HTTPS
          value: "false"
        - name: WEB_HTTPS_ONLY
          value: "false"
      imagePullSecrets:
      - name: glcr-auth

---

apiVersion: v1
kind: Service
metadata:
  name: arcx-public-ui-web-service
  namespace: arc-x-public-ui-236-dev
spec:
  ports:
  - port: 443
    protocol: TCP
    target_port: 80
    name: https
  selector:
    app: arcx-public-ui-web

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arcx-public-ui-web-ingress
  namespace: arc-x-public-ui-236-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    nginx.ingress.kubernetes.io/auth-tls-secret: arc-x-public-ui-236-dev/arc-x-cert
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
spec:
  rules:
  - host: arcx-public-ui.devsecops-dev.aws.epa.gov
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: arcx-public-ui-web-service
            port: 
              number: 443
  tls:
    - hosts:
      - arcx-public-ui.devsecops-dev.aws.epa.gov
      secretName: arc-x-cert
