
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcx-public-ui-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcx-public-ui-web

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: arcx-public-ui-web
    spec:
      containers:
      - name: web
        image: $CI_REGISTRY_IMAGE/public-ui-web:$CI_COMMIT_REF_SLUG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: arcx-public-ui-configmap
        env:
        - name: REDEPLOY_META
          value: $CI_JOB_ID-$CI_COMMIT_SHA
        - name: WEB_HTTPS
          value: "false"
        - name: WEB_HTTPS_ONLY
          value: "false"
      imagePullSecrets:
      - name: glcr-auth

---

apiVersion: v1
kind: Service
metadata:
  name: arcx-public-ui-web-service
spec:
  ports:
  - port: 80
  selector:
    app: arcx-public-ui-web

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arcx-public-ui-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    nginx.ingress.kubernetes.io/auth-tls-secret: ${KUBE_NAMESPACE}/arcx-tls-cert

spec:
  rules:
  - host: arcx.devsecops-prod.aws.epa.gov
    http:
      paths:
      - path: /
        pathType: Prefix    
        backend:
          service: 
            name: arcx-public-ui-web-service
            port : 
              number: 80
  - host: climateadaptation.epa.gov
    http:
      paths:
      - path: /
        pathType: Prefix    
        backend:
          service: 
            name: arcx-public-ui-web-service
            port : 
              number: 80
  tls:
  - hosts:
    - arcx.devsecops-prod.aws.epa.gov
    - climateadaptation.epa.gov
    secretName: arcx-tls-cert

